# Generated by Django 3.2.4 on 2021-07-14 14:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('PBL', '0003_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='date_posted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='post',
            name='request1',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='type',
            field=models.CharField(choices=[('Stationary', 'Stationary'), ('Notes', 'Notes'), ('Help in Project', 'Help in Project'), ('Other', 'Other')], default='', max_length=20, null=True),
        ),
    ]
