# Generated by Django 3.2.4 on 2021-07-14 16:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PBL', '0004_auto_20210714_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 14, 22, 19, 45, 372829)),
        ),
    ]
